import { SheetTemplate } from '../types';

export const SHEET_TEMPLATES: Record<string, SheetTemplate> = {
  'avery-24': {
    id: 'avery-24',
    name: '24 Stickers per vel (70 × 37 mm)',
    description: 'Standaardstickers (3 kolommen × 8 rijen). Populair formaat (Avery 3474 / Herma 4459).',
    columns: 3,
    rows: 8,
    labelsPerPage: 24,
    labelWidthMm: 70,
    labelHeightMm: 37,
    marginTopMm: 0.5,
    marginBottomMm: 0.5,
    marginLeftMm: 0,
    marginRightMm: 0,
    gapHorizontalMm: 0,
    gapVerticalMm: 0,
    showCutLines: false,
  },
  'avery-16': {
    id: 'avery-16',
    name: '16 Stickers per vel (105 × 37 mm)',
    description: 'Brede stickers (2 kolommen × 8 rijen). Extra veel ruimte voor lange productnamen.',
    columns: 2,
    rows: 8,
    labelsPerPage: 16,
    labelWidthMm: 105,
    labelHeightMm: 37,
    marginTopMm: 0.5,
    marginBottomMm: 0.5,
    marginLeftMm: 0,
    marginRightMm: 0,
    gapHorizontalMm: 0,
    gapVerticalMm: 0,
    showCutLines: false,
  },
  'compact-21': {
    id: 'compact-21',
    name: '21 Stickers per vel (70 × 42.4 mm)',
    description: '3 kolommen × 7 rijen. Iets hogere stickers (Avery 3658).',
    columns: 3,
    rows: 7,
    labelsPerPage: 21,
    labelWidthMm: 70,
    labelHeightMm: 42.4,
    marginTopMm: 0.1,
    marginBottomMm: 0.1,
    marginLeftMm: 0,
    marginRightMm: 0,
    gapHorizontalMm: 0,
    gapVerticalMm: 0,
    showCutLines: false,
  },
  'custom': {
    id: 'custom',
    name: 'Aangepast formaat',
    description: 'Stel zelf rijen, kolommen en marges in.',
    columns: 3,
    rows: 8,
    labelsPerPage: 24,
    labelWidthMm: 70,
    labelHeightMm: 37,
    marginTopMm: 5,
    marginBottomMm: 5,
    marginLeftMm: 5,
    marginRightMm: 5,
    gapHorizontalMm: 2,
    gapVerticalMm: 2,
    showCutLines: true,
  },
};

export const DEFAULT_TEMPLATE = SHEET_TEMPLATES['avery-24'];
